name: CD
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'master' }}

permissions: {}

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    services:
      memcached:
        image: memcached:1.6.12
        ports:
          - 11211:11211
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: '3.14'
      - name: Install build dependencies
        run: |
          pip install --upgrade pip build setuptools setuptools_scm
      - name: Build sdist
        run: |
          python -m build --sdist
          ls -l dist
          python -c "import setuptools_scm; print(setuptools_scm.get_version())"
      - name: Install test dependencies
        run: |
          sudo apt-get update -y -q
          sudo apt-get install -y -q libmemcached-dev
          pip install --upgrade -r ./requirements_test.txt
          pip install dist/*.tar.gz
      - name: Run tests
        run: python bin/runtests.py -v tests --with-doctest
      - name: Upload artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: dist
          path: dist/*.tar.gz

  generate_wheels_matrix:
    name: Generate wheels matrix
    runs-on: ubuntu-latest
    outputs:
      include: ${{ steps.set-matrix.outputs.include }}
    steps:
      - uses: actions/checkout@v6.0.1
      - name: Install cibuildwheel
        run: pipx install cibuildwheel==3.3.1
      - id: set-matrix
        run: |
          MATRIX=$(
            {
              cibuildwheel --print-build-identifiers --platform linux \
              | jq -nRc '{"only": inputs, "os": "ubuntu-22.04"}' \
              | sed -e '/aarch64/s|ubuntu-22.04|ubuntu-22.04-arm|' \
              && cibuildwheel --print-build-identifiers --platform macos \
              | jq -nRc '{"only": inputs, "os": "macos-latest"}'
            } | jq -sc
          )
          echo "include=$MATRIX"
          echo "include=$MATRIX" >> $GITHUB_OUTPUT

  build_wheels:
    name: Build for ${{ matrix.only }}
    needs: [generate_wheels_matrix]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate_wheels_matrix.outputs.include) }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3.7.0
        with:
          platforms: all
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.1
        with:
          only: ${{ matrix.only }}
      - name: Upload wheels
        uses: actions/upload-artifact@v6.0.0
        with:
          path: ./wheelhouse/*.whl
          name: pylibmc2-${{ matrix.only }}

  release:
    name: Create GitHub release
    needs:
      - build_wheels
      - build_sdist
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v7.0.0
        with:
          pattern: pylibmc2-*
          merge-multiple: true
          path: wheels
      - name: Download sdist artifact
        uses: actions/download-artifact@v7.0.0
        with:
          name: dist
          path: dist
      - name: Release on GitHub
        uses: softprops/action-gh-release@v2.5.0
        with:
          draft: true
          files: |
            wheels/*.whl
            dist/*.tar.gz

  # TODO: Copied from the old workflow. It's not tested yet.
  #upload_pypi:
  #  needs: [build_wheels, build_sdist]
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/download-artifact@v3
  #      with:
  #        name: artifact
  #        path: dist

  #    - uses: actions/download-artifact@v3
  #      with:
  #        name: wheels
  #        path: dist

  #    - name: Publish to PyPI
  #      uses: pypa/gh-action-pypi-publish@master
  #      with:
  #        user: ${{ secrets.PYPI_USERNAME }}
  #        password: ${{ secrets.PYPI_PASSWORD }}
